User belongs to experiment group 'AlwaysDisplayTestExplorer - experiment'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - control'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
> conda --version
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> python ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> pyenv root
Error 2020-11-10 03:41:56: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/root/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/root/.config/Code/User/settings.json')
	at _handleError (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:730:838)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:9:168994)
	at async p.doesFileNeedToBeFixed (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:963651)
	at async /root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962778
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962724)
	at async p.updateTestSettings (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962351)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Error 2020-11-10 03:41:56: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/osboxes/Desktop/Aparare/IDS/Methods/.vscode/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/osboxes/Desktop/Aparare/IDS/Methods/.vscode/settings.json')
	at _handleError (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:730:838)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:9:168994)
	at async p.doesFileNeedToBeFixed (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:963651)
	at async /root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962778
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962724)
	at async p.updateTestSettings (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962351)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Python interpreter path: /usr/bin/python3
> pyenv root
> pyenv root
> pyenv root
Error 2020-11-10 03:41:56: Failed to activate a workspace, Class name = y, completed in 1055ms, has a falsy return value, Arg 1: <Uri:/home/osboxes/Desktop/Aparare/IDS/Methods/dns.py>, Return Value: undefined [TypeError: Cannot read property 'fileHash' of undefined
	at E.updateCachedInterpreterInformation (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:858569)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async E.getInterpreterDetails (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:857023)
	at async C.activate (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:47:301243)
	at async Promise.all (index 4)
	at async y.activateWorkspace (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:47:296505)]
Error 2020-11-10 03:41:56: Failure during activation. [TypeError: Cannot read property 'fileHash' of undefined
	at E.updateCachedInterpreterInformation (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:858569)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async E.getInterpreterDetails (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:857023)
	at async C.activate (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:47:301243)
	at async Promise.all (index 4)
	at async y.activateWorkspace (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:47:296505)]
Error 2020-11-10 03:41:56: sendStartupTelemetry() failed. [TypeError: Cannot read property 'fileHash' of undefined
	at E.updateCachedInterpreterInformation (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:858569)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async E.getInterpreterDetails (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:857023)
	at async C.activate (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:47:301243)
	at async Promise.all (index 4)
	at async y.activateWorkspace (/root/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:47:296505)]
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> pyenv root
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text /home/osboxes/Desktop/Aparare/IDS/Methods/dns.py
cwd: /home/osboxes/Desktop/Aparare/IDS/Methods
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text /home/osboxes/Desktop/Aparare/IDS/Methods/dns.py
cwd: /home/osboxes/Desktop/Aparare/IDS/Methods
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import pylint"
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import pylint"
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import pylint"
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import pylint"

Linter 'pylint' is not installed. Please install it or select another linter".
Error: Module 'pylint' not installed.
> pyenv root
> pyenv root
> conda --version
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import pip"
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import pip"
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import pylint"
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import pylint"
